baseURL = "https://jonlz.com/"
languagecode = "en"
defaultcontentlanguage = "en"
title = "Jon Lazar"
theme = "hugo-code"

paginate = 20
canonifyurls = true

# https://github.com/luizdepra/hugo-coder/wiki/Configurations
[params]
	author = "Jon Lazar"
	info = "iOS Engineer"
	description = "Jon Lazar's technical website"
	keywords = "jon,lazar,ios,mobile,engineering"

	footercontent = ""
	hidecredits = true
	hidecopyright = false

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/JonLz"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/jonlazar"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 3
    url = "mailto:jon.lazar@gmail.com"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "/projects/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"