name: Docker Image CI

on:
 push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
    - name: Build the Docker image
      run: docker build .
      
